accepted = [
    "Apache-2.0",
    "MIT",
    "Zlib",
    "MIT-0",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "OFL-1.1",
    "CC0-1.0",
    "ISC",
    "LicenseRef-UFL-1.0",
    "AGPL-3.0",
]
