[package]
resolver = "2"
name = "rhythm-engine"
version = "0.1.0"
authors = ["iiYese iiyese@outlook.com"]
edition = "2021"

[dependencies]
bevy = { version = "0.7.0", features = ["dynamic"] }
bevy_prototype_lyon = "0.5.0"
noisy_float = "0.2.0"
tinyvec = "1.5.1"
