[package]
resolver = "2"
name = "rhythm-engine"
version = "0.1.0"
authors = ["iiYese iiyese@outlook.com"]
edition = "2021"

[dependencies]
derive_more = "0.99.17"
bevy = { version = "0.7.0", features = ["dynamic"] }
bevy_prototype_lyon = "0.5.0"
noisy_float = "0.2.0"
tinyvec = "1.5.1"
itertools = "0.10.3"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
