[package]
name = "Rythm-Engine"
version = "0.1.0"
authors = ["iiYese"]
edition = "2018"

[features]
default = ["std"]

std = ["glam/std"]
libm = ["glam/libm"]

[dependencies]
glam = { version = "0.13.0", default-features = false, features = ["mint"] }
ggez = "0.6.0-rc1"
lyon_geom = "0.17.0"
cute = "0.3.0"
duplicate = "0.2.9"
undo = "0.46.2"

