[package]
resolver = "2"
name = "rhythm-engine"
version = "0.2.0"
authors = ["iiYese"]
edition = "2021"

[features]

[dependencies]
wgpu = "0.12.0"
winit = "0.26.0"
cgmath = "0.18.0"
env_logger = "0.9.0"
log = "0.4.14"
pollster = "0.2.4"
bytemuck = { version = "1.7.3", features = [ "derive" ] }
