[package]
resolver = "2"
name = "rhythm-engine"
version = "0.1.0"
authors = ["iiYese"]
edition = "2018"

[features]
default = ["std"]

std = ["glam/std"]
libm = ["glam/libm"]

[dependencies]
glam = { version = "0.13.0", default-features = false, features = ["mint"] }
ggez = "0.6.0" #{ git = "https://github.com/ggez/ggez", branch = "devel" }
lyon_geom = "0.17.0"
duplicate = "0.3"
undo = "0.46.2"
tinyvec = "1.3.1"
serde = "1.0.130"

wgpu = "0.11.0"
winit = "0.25.0"
cgmath = "0.18.0"
env_logger = "0.9.0"
log = "0.4.14"
pollster = "0.2.4"
